
mybatis:
  config-location: classpath:SqlMapConfig.xml
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vue_study?serverTimezone=UTC
    username: root
    password: 174878
  #两个设置让自定义ExceptionHandler生效
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  redis:
    host: 192.168.74.134
    port: 6379
    password: 174878
#    url: redis://root:174878@192.168.74.134:6379
server:
  port: 8181

